import json
from groq import AsyncGroq
from app.config import settings


def get_groq_client() -> AsyncGroq:
    """Get an AsyncGroq client instance."""
    return AsyncGroq(api_key=settings.GROQ_API_KEY)


async def analyze_plagiarism(
    chunk_text: str,
    web_sources: list[dict],
) -> dict:
    """
    Analyze a text chunk for plagiarism against web sources using Groq LLM.

    Args:
        chunk_text: The text chunk from the uploaded document.
        web_sources: List of web search results to compare against.

    Returns:
        Dict with plagiarism_score (0-100), matched_sources, and analysis.
    """
    if not settings.GROQ_API_KEY:
        return {"plagiarism_score": 0, "matched_sources": [], "analysis": "API key not configured"}

    client = get_groq_client()

    # Build the source context
    sources_context = ""
    for i, source in enumerate(web_sources[:5]):
        sources_context += f"\n--- Source {i+1} ---\n"
        sources_context += f"URL: {source.get('url', 'N/A')}\n"
        sources_context += f"Title: {source.get('title', 'N/A')}\n"
        sources_context += f"Content: {source.get('content', 'N/A')}\n"

    prompt = f"""You are an expert plagiarism detection system. Analyze the following text chunk from a student's document and compare it against the web sources found online.

DOCUMENT TEXT:
\"\"\"{chunk_text}\"\"\"

WEB SOURCES FOUND:
{sources_context if sources_context.strip() else "No matching web sources found."}

INSTRUCTIONS:
1. Compare the document text with each web source for similarity.
2. Check for direct copying, paraphrasing, or close rewording.
3. Assign a plagiarism score from 0 to 100:
   - 0-10: Original content, no matches found
   - 11-30: Minor similarities, likely coincidental
   - 31-60: Moderate similarity, possible paraphrasing
   - 61-80: High similarity, likely plagiarized with modifications
   - 81-100: Very high match, direct copying detected

RESPOND IN THIS EXACT JSON FORMAT ONLY (no extra text):
{{
  "plagiarism_score": <number 0-100>,
  "matched_sources": [
    {{
      "url": "<source url>",
      "title": "<source title>",
      "similarity": <number 0-100>,
      "matched_text": "<specific text from the source that matches>"
    }}
  ],
  "analysis": "<brief 1-2 sentence explanation of findings>"
}}"""

    try:
        response = await client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content": "You are a plagiarism detection engine. Respond ONLY with valid JSON."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.1,
            max_tokens=1000,
        )

        result_text = response.choices[0].message.content.strip()

        # Try to parse JSON from the response
        # Handle cases where model wraps JSON in markdown code blocks
        if result_text.startswith("```"):
            result_text = result_text.split("```")[1]
            if result_text.startswith("json"):
                result_text = result_text[4:]
            result_text = result_text.strip()

        return json.loads(result_text)

    except json.JSONDecodeError:
        return {"plagiarism_score": 0, "matched_sources": [], "analysis": "Failed to parse AI response"}
    except Exception as e:
        return {"plagiarism_score": 0, "matched_sources": [], "analysis": f"Error: {str(e)}"}


async def detect_ai_writing(chunk_text: str) -> dict:
    """
    Analyze a text chunk for AI-generated content using Groq LLM.

    Checks for patterns typical of AI writing: uniform perplexity,
    lack of burstiness, formulaic structures, etc.

    Args:
        chunk_text: The text chunk to analyze.

    Returns:
        Dict with ai_score (0-100) and analysis explanation.
    """
    if not settings.GROQ_API_KEY:
        return {"ai_score": 0, "analysis": "API key not configured"}

    client = get_groq_client()

    prompt = f"""You are an expert AI writing detection system. Analyze the following text and determine the likelihood that it was generated by an AI language model (like ChatGPT, Claude, etc.).

TEXT TO ANALYZE:
\"\"\"{chunk_text}\"\"\"

ANALYSIS CRITERIA:
1. **Perplexity**: AI text tends to have uniform, low perplexity (predictable word choices).
2. **Burstiness**: Human writing has variable sentence lengths and complexity. AI tends to be more uniform.
3. **Vocabulary patterns**: AI often uses certain phrases like "it's important to note", "in conclusion", "furthermore", "delve into".
4. **Structure**: AI text is often overly organized with clear transitions.
5. **Creativity markers**: Human text has unique analogies, personal voice, and idiosyncratic expressions.

SCORING:
- 0-15: Definitely human-written
- 16-35: Mostly human, minor AI-like patterns
- 36-55: Mixed signals, uncertain
- 56-75: Likely AI-generated with some human editing
- 76-100: Very likely AI-generated

RESPOND IN THIS EXACT JSON FORMAT ONLY (no extra text):
{{
  "ai_score": <number 0-100>,
  "analysis": "<brief 2-3 sentence explanation of why this score was assigned, citing specific evidence>"
}}"""

    try:
        response = await client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content": "You are an AI writing detection engine. Respond ONLY with valid JSON."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.1,
            max_tokens=500,
        )

        result_text = response.choices[0].message.content.strip()

        # Handle markdown code blocks
        if result_text.startswith("```"):
            result_text = result_text.split("```")[1]
            if result_text.startswith("json"):
                result_text = result_text[4:]
            result_text = result_text.strip()

        return json.loads(result_text)

    except json.JSONDecodeError:
        return {"ai_score": 0, "analysis": "Failed to parse AI response"}
    except Exception as e:
        return {"ai_score": 0, "analysis": f"Error: {str(e)}"}
